apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  description: "test"
  annotations:
    gcp/cloudrun-service: "test"
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/guests"
