steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/vibe-cabral/cabral-petstore-api-backstage:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/vibe-cabral/cabral-petstore-api-backstage:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cabral-petstore-api-backstage'
      - '--image'
      - 'gcr.io/vibe-cabral/cabral-petstore-api-backstage:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--project'
      - 'vibe-cabral'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/vibe-cabral/cabral-petstore-api-backstage:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
